// This file is auto-generated by @hey-api/openapi-ts

export { client, type CreateClientConfig } from './client.gen';
export { MailjetResource, type Options } from './sdk.gen';
export type { CheckWebhookConfigurationRequest, CheckWebhookConfigurationResponse, ClientOptions, ConfigureNowData, ConfigureNowErrors, ConfigureNowResponse, ConfigureNowResponses, GetConfigurationData, GetConfigurationErrors, GetConfigurationResponse, GetConfigurationResponses } from './types.gen';
