// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ConfigureNowData, ConfigureNowResponse, GetConfigurationData, GetConfigurationResponse } from './types.gen';

export class MailjetResource {
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static configureNow(data: ConfigureNowData = {}): CancelablePromise<ConfigureNowResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/newsletter-studio-mailjet/configure-now',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token'
            }
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static getConfiguration(data: GetConfigurationData = {}): CancelablePromise<GetConfigurationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/management/api/newsletter-studio-mailjet/get-configuration',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                401: 'The resource is protected and requires an authentication token'
            }
        });
    }
    
}