// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54108/' | (string & {});
};

export type CheckWebhookConfigurationRequest = {
    settings: {
        [key: string]: unknown;
    };
    workspaceKey: string;
    baseUrl: string;
};

export type CheckWebhookConfigurationResponse = {
    webhookUrl: string;
    isBaseUrlLocalhost: boolean;
};

export type ConfigureNowData = {
    body: CheckWebhookConfigurationRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/newsletter-studio-mailjet/configure-now';
};

export type ConfigureNowErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConfigureNowResponses = {
    /**
     * OK
     */
    200: CheckWebhookConfigurationResponse;
};

export type ConfigureNowResponse = ConfigureNowResponses[keyof ConfigureNowResponses];

export type GetConfigurationData = {
    body: CheckWebhookConfigurationRequest;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/newsletter-studio-mailjet/get-configuration';
};

export type GetConfigurationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConfigurationResponses = {
    /**
     * OK
     */
    200: CheckWebhookConfigurationResponse;
};

export type GetConfigurationResponse = GetConfigurationResponses[keyof GetConfigurationResponses];
